language: python
python: '2.7'
sudo: required
env:
  global:
  - TOX_ENV=py27
  - SITE_URL="https://artbio.github.io/startbio/"
  - GH_USER_NAME="Christophe Antoniewski"
  - GH_USER_EMAIL="drosofff@gmail.com"
  - GH_REF="github.com/ARTbio/startbio.git"
install: true
script:
- bash ./deploy.sh
