name: Publish
on: [push, pull_request]

jobs:
  build:
    name: Build readthedocs
    runs-on: ubuntu-latest
    steps:
      - name: mkdocs
        run: |
          python -m pip install -U pip mkdocs mkdocs-material pygments pymdown-extensions
      - name: Build
        run: |
          mkdir mkdocs_build
          cd mkdocs_build
          # Initialize gh-pages checkout
          DATE=`date`
          git clone https://github.com/ARTbio/startbio.git
          cd startbio
          shuf docs/Covid-19/youtube.md -o shuffle.txt
          mv shuffle.txt docs/Covid-19/youtube.md
          git config credential.helper "store --file=.git/credentials"
          echo "https://${{ secrets.GITHUB_TOKEN }}:@github.com" > .git/credentials
          mkdocs gh-deploy --clean -m "gh-deployed by travis $DATE"
