name: Publish
env:
  secure: 0XB4cBHOEV7L5Yz9OELPsO4T4F7NqT6HovivMaQRkyJYX6NPr74FVMrEpZEYUYlNeh7wEUF7rvK2u+3RuHthZaeGIMLD7hgflNjbiYCojW3TegJS2ks77mJ8agT2KfaHWWVCw9EOW0Zc4j4CCwBl1WfU4Zi12lkT4CS6KP/LWsHUGrPkLPOh/bSzl7dWjs6gMksh+Gzd+7XvKlP9rTM8cDXh3idMCeThQu8bo55QK+PpEkxoPGOKZqb1ZEaGgupnxXyZJfbStKBW9yUhISmyK0Nw169+7stZ+YbhOnQmIMStljD/ogAeaOAnVccSUiBqat6VmgoDb7+DyOBtmLGm96/Pe2Os5YgIhsZgiO1fJTR5m0w/FR7rouywPJNJPbvIrHLY1pB/ArrYYTISHrKiXq+cQmFtMNgOoZ7/IBiy7jVi/0UboFyMPZTyktnaoxSE9WzUrVg+y+q0LGc3+o9mQZJbO1fZDgh7WZ7fGAwsUpUZdujN7T/xw5IrdatM7VIyfywwi6U+5y/P7Qu3k4L3OkbIpN6D9HRPRksC0dA7YAaRqrfV3DbxxO72UjFajidol3lD9NRTFZjAVC3SqtD+aMG1W4u3JfjMw9ZCQdT8sKfXOhF+BX6eryaauTRJ/aN5/kOugRMwIWwXq7l1XsA6DrTCcJl9S+51fuWaU7ZQNVQ=
on: [push, pull_request]

jobs:
  build:
    name: Build readthedocs
    runs-on: ubuntu-latest
    steps:
    - uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: ${{secrets.GH_CRED}}
    - name: mkdocs
      run: |
        python -m pip install -U pip mkdocs mkdocs-material pygments pymdown-extensions
    - name: Build
      uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: ${{secrets.GH_CRED}}
      run: |
        mkdir mkdocs_build
        cd mkdocs_build
        # Initialize gh-pages checkout
        DATE=`date`
        git clone https://github.com/ARTbio/startbio.git
        cd startbio
        shuf docs/Covid-19/youtube.md -o shuffle.txt
        mv shuffle.txt docs/Covid-19/youtube.md
        mkdocs gh-deploy --clean -m "gh-deployed by travis $DATE"
